// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAgibTdJQs8Orq4QPQRBhHw5c2OLBvOERQ',
  //   appId: '1:525100777741:web:6ed8d441b94ed39304f044',
  //   messagingSenderId: '525100777741',
  //   projectId: 'mybloodbuddie',
  //   authDomain: 'mybloodbuddie.firebaseapp.com',
  //   storageBucket: 'mybloodbuddie.appspot.com',
  //   measurementId: 'G-JQHML1HDRF',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcljpE8B9BdBNq01Wynqa4lP-ZIcstY3U',
    appId: '1:355566592453:android:5956fab2f5842f4050ebac',
    messagingSenderId: '355566592453',
    projectId: 'mybloodbuddy-4065e',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcljpE8B9BdBNq01Wynqa4lP-ZIcstY3U',
    appId: '1:355566592453:ios:95d25bc0e49d299150ebac',
    messagingSenderId: '355566592453',
    projectId: 'mybloodbuddy-4065e',
    iosBundleId: 'com.example.mybb',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAwxhsHPGv188zSfXZuyj9do_1x1bNKxm0',
  //   appId: '1:525100777741:ios:91bd8dbd654ab0a104f044',
  //   messagingSenderId: '525100777741',
  //   projectId: 'mybloodbuddie',
  //   storageBucket: 'mybloodbuddie.appspot.com',
  //   iosBundleId: 'com.example.mybb',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyAgibTdJQs8Orq4QPQRBhHw5c2OLBvOERQ',
  //   appId: '1:525100777741:web:6915b78cbe66feda04f044',
  //   messagingSenderId: '525100777741',
  //   projectId: 'mybloodbuddie',
  //   authDomain: 'mybloodbuddie.firebaseapp.com',
  //   storageBucket: 'mybloodbuddie.appspot.com',
  //   measurementId: 'G-80J24Q13XQ',
  // );

}